model:
  lr: 0.001              # Learning rate for the optimizer
  hidden_dim: 256         # Dimension of hidden layers in the model
  forecast_steps: 1       # Number of autoregressive steps for forecasting
  compile: true           # Whether to compile the model
  num_layers: 1           # Number of ADR processing layers
  splitting_scheme: "lie" # Operator splitting method: "lie" or "strang"
  warmup_steps: 1000
  gradient_clip_val: 1.0
  base_dt: 21600          # 6 hours * 3600 seconds
  checkpoint_path: null

dataset:
  dataset_dir: /path/to/dataset/
  start_date: 1970-01-01  # Start date for the dataset (YYYY-MM-DD)
  end_date: 1970-03-31    # End date for the dataset (YYYY-MM-DD)
  train_ratio: 0.8        # Ratio of data used for training (rest for validation)
  batch_size: 32          # Number of samples per batch
  num_workers: 4          # Number of workers for dataloader

trainer:
  max_epochs: 100
  num_devices: 1
  accelerator: gpu
  use_amp: true
  early_stopping: false
  print_losses: false

features:
  pressure_levels: # Added to atmospheric variable names
    - 50
    - 100
    - 150
    - 200
    - 250
    - 300
    - 400
    - 500
    - 600
    - 700
    - 850
    - 925
    - 1000

  base:
    atmospheric:
      - geopotential
      - u_component_of_wind
      - v_component_of_wind
      - specific_humidity
      - temperature
      - vertical_velocity

  input:
    atmospheric: ${features.base.atmospheric} # Same as output and base
    surface:
      - 10m_u_component_of_wind
      - 10m_v_component_of_wind
      - 2m_temperature
      - mean_sea_level_pressure
    constants:
      - geopotential_at_surface
      - land_sea_mask
      - cos_latitude
      - cos_longitude
      - sin_longitude
    forcings:
      - toa_radiation
      - sin_time_of_day
      - cos_time_of_day
      - sin_year_progress
      - cos_year_progress

  output:
    atmospheric: ${features.base.atmospheric} # Same as input and base
    surface:
      - 10m_u_component_of_wind
      - 10m_v_component_of_wind
      - 2m_temperature
      - mean_sea_level_pressure
      - total_precipitation_6hr # precipitation is only an output

variable_loss_weights:
  atmospheric:
    u_component_of_wind: 1.0
    geopotential: 1.0
    v_component_of_wind: 1.0
    vertical_velocity: 1.0
    specific_humidity: 1.0
    temperature: 1.0
  surface:
    mean_sea_level_pressure: 1.0
    10m_u_component_of_wind: 1.0
    2m_temperature: 1.0
    total_precipitation_6hr: 1.0
    10m_v_component_of_wind: 1.0
