model:
  lr: 0.001               # Learning rate for the optimizer
  hidden_dim: 256         # Dimension of hidden layers in the model
  forecast_steps: 1       # Number of autoregressive steps for forecasting
  num_heads: 2            # Number of attention heads in the model
  dropout: 0.1            # Dropout rate for regularization
  use_layer_norm: true    # Whether to use layer norm in model
  compile: false          # Whether to compile the model
  num_layers: 4           # Number of ADR processing layers
  splitting_scheme: "lie" # Operator splitting method: "lie" or "strang"
  warmup_steps: 1000
  gradient_clip_val: 1.0

dataset:
  dataset_dir: /path/to/dataset/
  start_date: 1970-01-01  # Start date for the dataset (YYYY-MM-DD)
  end_date: 1970-03-31    # End date for the dataset (YYYY-MM-DD)
  train_ratio: 0.8        # Ratio of data used for training (rest for validation)
  batch_size: 32          # Number of samples per batch
  num_workers: 4          # Number of workers for dataloader

graph:
  cube_resolution: 90     # Cells per cube edge (default is 1 deg resolution)
  nearest_neighbors: 10
  mesh_neighbors: 6

trainer:
  max_epochs: 100
  num_devices: 1
  accelerator: gpu
  use_amp: false
  early_stopping: false
  print_losses: false

features:
  pressure_levels: # Added to atmospheric variable names
    - 50
    - 100
    - 150
    - 200
    - 250
    - 300
    - 400
    - 500
    - 600
    - 700
    - 850
    - 925
    - 1000
  base:
    atmospheric:
      - u_component_of_wind
      - geopotential
      - v_component_of_wind
      - vertical_velocity
      - specific_humidity
      - temperature

  input:
    atmospheric: ${features.base.atmospheric} # Same as output and base
    surface:
      - 10m_u_component_of_wind
      - 10m_v_component_of_wind
      - 2m_temperature
      - geopotential_at_surface
      - land_sea_mask
      - mean_sea_level_pressure

  output:
    atmospheric: ${features.base.atmospheric} # Same as input and base
    surface:
      - 10m_u_component_of_wind
      - 10m_v_component_of_wind
      - 2m_temperature
      - mean_sea_level_pressure
      - total_precipitation_6hr # precipitation is only an output
